#60 Add Map block component
bratislava/olo.sk pull request #225
Opened 2024-07-12 07:38 UTC by katarinazaprazna

2024-07-15 14:49 UTC, radoslavzeman requested changes

2024-07-15 14:49 UTC, radoslavzeman commented on next/src/components/common/Box/Map.tsx
> +            <div key={index} className="w-full">
Do we need an additional `div` here? Could we use `Fragment` instead? :)

2024-07-15 14:49 UTC, radoslavzeman commented on next/src/components/common/Box/Map.tsx
> +  if (!children?.length) return null
I would prefer to render the component also with no children (empty right part). It's more understandable for content admins if they see "bad looking" component than no component.

2024-07-15 14:49 UTC, radoslavzeman commented on next/src/components/common/MapPlaceholder.tsx
> +      height={220}
The map should adapt it's height depending on the content in the right part (rows), it should not have fixed dimensions.
The map can have fixed width.

2024-07-15 14:53 UTC, radoslavzeman reviewed
Nice and clean, please only reflect minor comments left in the review :)

2024-07-15 21:56 UTC, katarinazaprazna commented on next/src/components/common/Box/Map.tsx
> +            <div key={index} className="w-full">
We're using the `className` property on each of the divs present in the code, which, to my knowledge, makes the usage of fragments impossible

2024-07-15 22:01 UTC, katarinazaprazna commented on next/src/components/common/Box/Map.tsx
> +  if (!children?.length) return null
This is the pattern of rendering we're currently using in the rest of the code. In this case, our options would be 1. defaulting to rendering an empty rectangle or 2. rendering a map without markers. Is this something we want to consider doing?

2024-07-15 22:08 UTC, katarinazaprazna commented on next/src/components/common/MapPlaceholder.tsx
> +      height={220}
This was something I planned to revisit once implementing the actual, Mapbox mapping functionality. The placeholder is temporary

2024-07-16 14:16 UTC, radoslavzeman commented on next/src/components/common/Box/Map.tsx
> +            <div key={index} className="w-full">
If you remove `items-center` from parent div, you can use `Fragment` :)

2024-07-16 14:49 UTC, radoslavzeman approved these changes

2024-07-16 23:05 UTC, merged