#186 Format workshop dates in Mega Menu
bratislava/olo.sk pull request #345
Opened 2024-08-15 19:04 UTC by katarinazaprazna

- Format workshop dates using `js-joda`

2024-08-16 12:49 UTC, radoslavzeman requested changes
Please use native `toLocaleDateString` formatting instead of `js-joda` and uninstall `js-joda`.

2024-08-16 12:49 UTC, radoslavzeman commented on next/src/utils/getMostRecentWorkshopDate.ts
I am quite sure we can do this without additional date libraries, using native js datetime formatting functions.

Please do not install `js-joda` or other libraries.

2024-08-16 12:49 UTC, radoslavzeman commented on next/src/utils/getMostRecentWorkshopDate.ts
> +    .plusHours(2) // Convert implicit UCT to CET
This is a very bad solution. 2 hours difference from UTC is in CEST (summer time) while in CET (winter time) there is only 1 hour difference.
You NEVER want to add/subtract hours manually to "solve" timezones. ALWAYS use built-in functions (in plain ja e.g. `toLocalDateString`, but there is surely some in `js-joda` too.

2024-08-16 12:49 UTC, radoslavzeman commented on next/src/utils/getMostRecentWorkshopDate.ts
> +    .reduce((earliest, current) => (current.isBefore(earliest) ? current : earliest))
Could we just use native `sort` function on array of datetimes? I'm sure we can, if needed, convert array items to timestamp but sort should work on any Date formats.

2024-08-16 12:49 UTC, radoslavzeman commented on next/src/utils/getMostRecentWorkshopDate.ts
> +  return `${nextWorkshop.dayOfMonth()}. ${formattedMonth} ${nextWorkshop.year()} o ${formattedTime}`
Using native `toLocalDateString, we get also "o" in proper language :)

```
date.toLocaleDateString('sk-SK', {
  year: 'numeric',
  month: 'long',
  day: 'numeric',
  hour: 'numeric',
  minute: 'numeric',
})
```

This returns `20. decembra 2012 o 4:00`. 
Sorry for slovak text: Mesiac je vysklonovany, nie je v nominative, cize je tam "decembra", nie "december", ale to je uplne v poriadku.

2024-08-16 12:49 UTC, radoslavzeman commented on next/src/utils/getMostRecentWorkshopDate.ts
> +  return `${nextWorkshop.dayOfMonth()}. ${formattedMonth} ${nextWorkshop.year()} o ${formattedTime}`
Docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

We use this native formatiing also in `formatDate.ts` function.

2024-08-16 12:50 UTC, radoslavzeman commented on next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
> +              getMostRecentWorkshopDate(link.workshop?.data)
This will actually be optimised during compiling automatically, but for cleaner code, it would be nicer to put it into variable.

2024-08-16 13:15 UTC, katarinazaprazna commented on next/src/utils/getMostRecentWorkshopDate.ts
Thanks for the feedback! I'm used to resolving to date libraries whenever working with datetime data, as to avoid potential errors whilst parsing native `Date` objects. I can look into a plain JS solution

2024-08-19 10:26 UTC, radoslavzeman requested changes

2024-08-19 10:26 UTC, radoslavzeman commented on next/src/utils/getMostRecentWorkshopDate.ts
> +    // @ts-ignore
No `@ts-ignore` should be needed in production code. If so, let's discuss before merging

2024-08-19 10:31 UTC, radoslavzeman commented on next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
> +                : ''
Maybe we could make `subText` optional? It makes more sense that to pass empty string.

2024-08-19 10:31 UTC, radoslavzeman commented on next/src/utils/getMostRecentWorkshopDate.ts
> +  })
Please extract to a separate file `formatMostRecentWorkshopDate.ts` placed next to `formatDate.ts` file.
I would like to keep all formatting functions in one place (utils folder?).

2024-08-19 10:38 UTC, katarinazaprazna commented on next/src/utils/getMostRecentWorkshopDate.ts
> +    // @ts-ignore
The `@ts-ignore` is there so that we can directly compare the native dates as such: `firstWorkshop - secondWorkshop`. The compiler requires the type of number for such comparison. The easiest solution to getting rid of the `@ts-ignore` would be converting dates into timestamps

2024-08-19 10:43 UTC, katarinazaprazna commented on next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
> +                : ''
Thanks for the suggestion! In this case we expect each workshop to come with the `subText` though. The empty string is there for exceptional circumstances only. Isn't it better to handle exceptional cases as exemplified in the original code?

2024-08-19 10:56 UTC, radoslavzeman commented on next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
> +                : ''
Empty string in `subText` leads to double-gap in this case. For me, it makes sense to handle also "exceptional circumstances" such as "no workshops date in future properly by not providing `subText`.

![image](https://github.com/user-attachments/assets/0b21521f-319c-44ca-a2d8-2cf5e9c62f0e)

2024-08-19 11:18 UTC, radoslavzeman commented on next/src/utils/getMostRecentWorkshopDate.ts
> +    // @ts-ignore
So why not to do it? :)

2024-08-20 13:46 UTC, radoslavzeman approved these changes
Nice :)

2024-08-20 13:46 UTC, radoslavzeman commented on next/src/components/common/Card/MenuItemWorkshopCard.tsx
> +          {subText ? <Typography variant="p-small">{subText}</Typography> : null}
Following our patterns, please also make `subText` optional for consistency.

2024-08-20 14:22 UTC, merged