#352 Add Strapi Header component into Menu
bratislava/olo.sk pull request #372
Opened 2024-08-19 09:45 UTC by katarinazaprazna

2024-08-19 09:59 UTC, katarinazaprazna commented on next/src/services/graphql/queries/menu.gql
> +    links {
For each link in the header, we should ideally be able to specify its icon name. The links will be rendered as buttons, with each button rendering a specific icon. So far, the only link/button we display is "Kontakty". I assume that for the button's icon, we would hardcode the icon name string. Do we want to add an `iconName` field in Strapi as well? @radoslavzeman

2024-08-19 11:21 UTC, radoslavzeman commented on next/src/services/graphql/queries/menu.gql
> +    links {
I would add only one specific `contactsLink` into Strapi.

If there is need for more links, we can implement it later.

2024-08-19 11:22 UTC, radoslavzeman commented on next/src/services/graphql/queries/menu.gql
Please fix tab spaces :)

2024-08-20 13:54 UTC, radoslavzeman requested changes
Knowing how hard it is to migrate, I want to keep strapi components clean. Please rename the component.

2024-08-20 13:54 UTC, radoslavzeman commented on strapi/src/components/header-menu/header.json
Please move this strapi component into `items` and change the name from `header` to `menu header` (not only display name)

2024-08-20 14:49 UTC, radoslavzeman approved these changes
nice :)

2024-08-20 14:59 UTC, merged