#355 Retrieve the subText property from links
bratislava/olo.sk pull request #397
Opened 2024-08-21 09:39 UTC by katarinazaprazna

- Extend `useGetLinkProps` hook to retrieve additional properties from links

2024-08-22 09:20 UTC, radoslavzeman requested changes

2024-08-22 09:20 UTC, radoslavzeman commented on next/src/utils/useGetLinkProps.ts
> +    }
I don't think this should be part of this hook.

Getting links props (href, label, target) and getting subtext are to separate non-related "tasks", even though both are displayed on the same Card component. 

Similarly, we do not fetch article tag (or perex) through `useGetLinkProps` when displayed for example in carousel:
![image](https://github.com/user-attachments/assets/cc6e3e66-7bfd-4e61-98ff-d2785908a274)

Here I see that `getAdditionalLinkProps` mixes these two tasks.

2024-08-22 10:26 UTC, katarinazaprazna commented on next/src/utils/useGetLinkProps.ts
> +    }
I'll check how articles are being handled!

2024-08-26 07:58 UTC, radoslavzeman approved these changes

2024-08-26 07:58 UTC, radoslavzeman commented on next/src/components/common/NavBar/NavMenu/NavMenuSectionLink.tsx
> +    formatMostRecentWorkshopDate(link?.workshop?.data?.attributes?.dates) ?? ''
Just for clean code, I would write `?? null`

2024-08-26 07:58 UTC, radoslavzeman commented on next/src/components/common/NavBar/NavMenu/NavMenuSectionLink.tsx
> +          title={children ?? ''}
`children` are always string, so there is no need of `?? ''`

2024-08-26 07:58 UTC, radoslavzeman commented on next/src/components/common/NavBar/NavMenu/NavMenuSectionLink.tsx
> +          title={children ?? ''}
`children` are always string, so there is no need of `?? ''`

2024-08-26 07:58 UTC, radoslavzeman commented on next/src/utils/formatMostRecentWorkshopDate.ts
> +type WorkshopDates =
You can create for example `WorkhopDateItem` fragment in graphql file and use the generated frangment type (`WorkshopDateItemFragment`).

Anyway, I think that Strapi types datetimes as `any` unfortunately :/ (Or tell me if I am wrong) But still, this suggested approach would be nice to follow.

```graphql
fragment WorkshopDateItem on ComponentItemsWorkshopDate {
  datetime
}

fragment WorkshopSlugEntity on WorkshopEntity {
  __typename
  id
  attributes {
    title
    slug
    dates {
      ...WorkshopDateItem
    }
  }
}
```

2024-08-26 10:51 UTC, merged