#186 Ensure vertical dividers do not depend on hasDividers
bratislava/olo.sk pull request #466
Opened 2024-09-03 11:04 UTC by katarinazaprazna

2024-09-03 13:50 UTC, radoslavzeman requested changes

2024-09-03 13:50 UTC, radoslavzeman commented on next/src/components/common/NavBar/NavMenu/NavMenuContentCell.tsx
> +      {hasVerticalDivider ? <NavBarDivider variant="vertical" className="px-8" /> : null}
The comment says: "Dividers should not be a part of list elements" - it's still here :D 

Could we remove `hasVerticalDivider` prop completely from `NavMenuContentCell`?

Divider could be handled in main `<ul>` https://github.com/bratislava/olo.sk/pull/466/files#diff-f72eac8412ce36c6784216a3568fe0e0a1ed38b5069246fc46070bc21888fabeR37

2024-09-03 14:46 UTC, katarinazaprazna commented on next/src/components/common/NavBar/NavMenu/NavMenuContentCell.tsx
> +      {hasVerticalDivider ? <NavBarDivider variant="vertical" className="px-8" /> : null}
I wasn't sure about whether the menu will be tested today or not - if so, I made the changes necessary for the feature to work "optimally" from an outsider's perspective. I was planning to refactor this after today's testing

2024-09-03 14:55 UTC, katarinazaprazna commented on next/src/components/common/NavBar/NavMenu/NavMenuContentCell.tsx
> +      {hasVerticalDivider ? <NavBarDivider variant="vertical" className="px-8" /> : null}
Also, I wanted to ask you @radoslavzeman whether we want to keep `hasDividers` as a prop on section. Did we gather any comments from the content managers regarding the menu's complexity?

It is possible to handle the display of both vertical and horizontal dividers without the need of content managers to specify anything in Strapi. As of now, content managers enforce the display of horizontal dividers in the Newest articles, Branches and Workshops section cells via setting `hasDividers=TRUE`

2024-09-04 06:58 UTC, radoslavzeman commented on next/src/components/common/NavBar/NavMenu/NavMenuContentCell.tsx
> +      {hasVerticalDivider ? <NavBarDivider variant="vertical" className="px-8" /> : null}
Yes, 
> whether we want to keep hasDividers as a prop on section.

>As of now, content managers enforce the display of horizontal dividers in the Newest articles, Branches and Workshops section cells via setting hasDividers=TRUE

that's the behaviour what we (me and you) had already a discussion about and agreed on and it is also stated in the issue :)

2024-09-09 07:26 UTC, radoslavzeman approved these changes
Please fix comments as always and you can marge :)

2024-09-09 07:26 UTC, radoslavzeman commented on next/src/utils/useLatestArticles.ts
> +  )
There is no need to use `useMemo` because `useQuery` has its own caching.

Moreover, we stick to the approach by not optimising prematurely
https://imgeorgemor.medium.com/dont-get-fooled-by-usememo-and-usecallback-and-avoid-unnecessary-optimizations-2e7e854b487c

2024-09-09 07:26 UTC, radoslavzeman commented on next/src/utils/useLatestArticles.ts
> +    queryKey: ['latestArticles', { limit, locale }],
Just noticed that it's necessary to keep the query key consistent through the whole app.
I think we use `LatestArticles` with big letter (the same as the client function is called)

2024-09-09 12:04 UTC, merged