532 table of contents services
bratislava/olo.sk pull request #546
Opened 2024-09-23 10:27 UTC by jankaBehal

Implement Table of Contents for service page
Design for desktop devices
Design for mobile devices

<img width="931" alt="Snímka obrazovky 2024-09-23 094623" src="https://github.com/user-attachments/assets/5b7bd412-f2eb-4afa-9748-4f6953f08c51">

<img width="488" alt="Snímka obrazovky 2024-09-23 094929" src="https://github.com/user-attachments/assets/1f36626f-4136-40a4-83a1-ca77fe0e3d75">

<img width="485" alt="Snímka obrazovky 2024-09-23 100303" src="https://github.com/user-attachments/assets/fa2d359b-7594-47a1-b00a-e831933d775f">

2024-09-25 09:19 UTC, radoslavzeman requested changes
Nice job, I wrote you some comments, mostly related conventions and good practices. We can discuss them in person :)

2024-09-25 09:29 UTC, jankaBehal commented on next/src/components/common/TableOfContents/Content.tsx
> +  const handleOnClick = (id: string) => {
ok thank you

2024-09-25 11:05 UTC, jankaBehal commented on next/src/components/common/TableOfContents/useHeadings.ts
> +  }, [rootId])
yes because document is not defined on server side until useEffect happens

2024-09-25 13:31 UTC, radoslavzeman commented on next/src/components/common/TableOfContents/useHeadings.ts
> +  }, [rootId])
Would it be possible to use `useIsClient` from `usehooks-ts`?
```
const isClient = useIsClient()

const headings = isClient ? ... : []
```

2024-09-25 19:22 UTC, jankaBehal commented on next/src/components/common/Typography/Typography.tsx
> +        }
I did it this way in order not to have id defined where it is not used to purpose of Table of Content

2024-09-26 14:51 UTC, radoslavzeman commented on next/src/components/common/TableOfContents/Content.tsx
> +                key={heading.id}
Is the `key` needed here? :D

2024-09-27 08:04 UTC, merged