#141 Handle color contrast issues in Slider
bratislava/olo.sk pull request #548
Opened 2024-09-23 14:27 UTC by katarinazaprazna

2024-09-23 14:54 UTC, radoslavzeman commented on next/src/components/sections/homepage/HeroHomepageSection.tsx
> +          {slides?.length ? <Slider slides={filteredSlides} /> : null}
Once you check `slides` length, but then you pass `filteredSlides` as prop.

Either check the lenght of `filteredSlides` or leave it to `Slider` component to deal with zero slides.

2024-09-23 14:54 UTC, radoslavzeman commented on next/src/components/common/Slider/Slider.tsx
> +const Slider = ({ slides, backgroundColor = '#F1B434' }: SliderProps) => {
I would be better to use a colour from tailwind config instead of hardcoded value. You can import the tailwind theme, or just colours if they are in separate file.

2024-09-23 14:54 UTC, radoslavzeman commented on next/src/components/common/Slider/Slider.tsx
> +                ) : null}
Would it be possible to apply `invertedTypographyClassNames` to the div wrapping both Typographies?

2024-09-23 14:57 UTC, katarinazaprazna commented on next/src/components/sections/homepage/HeroHomepageSection.tsx
> +          {slides?.length ? <Slider slides={filteredSlides} /> : null}
That was an accident, thanks for catching that

2024-09-23 15:11 UTC, katarinazaprazna commented on next/src/components/common/Slider/Slider.tsx
> +const Slider = ({ slides, backgroundColor = '#F1B434' }: SliderProps) => {
I'll try accessing the colors from the config :)

2024-09-26 07:44 UTC, radoslavzeman requested changes

2024-09-26 07:44 UTC, radoslavzeman commented on next/src/components/common/Slider/Slider.tsx
> +const Slider = ({ slides, backgroundColor = '#F1B434' }: SliderProps) => {
Sorry, I realised it just now.
The colour should be set for each slide separately, as it is a field in each slide:
![image](https://github.com/user-attachments/assets/f958595a-5fe0-4993-85b0-82fa7f6f03c5)

2024-09-26 09:29 UTC, radoslavzeman approved these changes

2024-09-26 09:32 UTC, merged