#386 Create header for Careers page
bratislava/olo.sk pull request #560
Opened 2024-09-24 19:50 UTC by katarinazaprazna

- Create Careers section in Strapi
- Create React component `CareersPageHeader`
- Embed video (via iframe) within the header
- Extract the UI logic from `ImageAndTextOverlappedSection` into a separate component to allow reuse

<img width="728" alt="Screenshot 2024-09-23 at 13 17 02" src="https://github.com/user-attachments/assets/38773f36-56b8-4cce-9e34-86e246d2f315">

2024-09-25 08:04 UTC, katarinazaprazna commented on next/src/components/sections/headers/CareersPageHeader.tsx
> +        <div className="flex flex-col gap-4 pb-6 lg:gap-6 lg:py-0">
Potential adjustment: hide this `div` when both `title` and `text` are `undefined` or `null`

2024-09-25 08:06 UTC, katarinazaprazna commented on next/src/components/common/Image/ImageAndTextOverlapped.tsx
> +  image?: UploadImageSrcEntityFragment | UploadImageEntityFragment | null
Suggestions about how this type can be adjusted are welcome

2024-09-25 08:07 UTC, katarinazaprazna commented on next/src/components/common/Image/ImageAndTextOverlapped.tsx
> +      // @ts-ignore
Since the `UploadImageSrcEntityFragment` type does not have `alternativeText` attribute

2024-09-26 08:09 UTC, radoslavzeman requested changes
Several suggestions :)

2024-09-26 08:09 UTC, radoslavzeman commented on next/src/components/sections/headers/CareersPageHeader.tsx
> +        <div className="flex flex-col gap-4 pb-6 lg:gap-6 lg:py-0">
Could we just use `HeaderTitleText` as it is in other header sections?

2024-09-26 08:09 UTC, radoslavzeman commented on next/src/components/sections/headers/CareersPageHeader.tsx
> +          <Video url={videoUrl} ariaLabel={t('pageHeaderCareers.aria.videoTitle')} />
I would be more sustainable to add this aria label as a field into Strapi.

2024-09-26 08:09 UTC, radoslavzeman commented on strapi/src/components/header-sections/careers.json
> +    "imageTitle": {
The name `imageTitle` feels kind of confusing :D Maybe it's a `claim` and `claimImage`?

2024-09-26 08:09 UTC, radoslavzeman commented on next/src/components/common/Video/Video.tsx
> +    <div className="relative w-full overflow-hidden rounded-3xl pb-[56.25%]">
Could we use `aspect-video` instead of hacky padding? (I don't completely understand where this number comes from) https://tailwindcss.com/docs/aspect-ratio

2024-09-26 08:34 UTC, katarinazaprazna commented on strapi/src/components/header-sections/careers.json
> +    "imageTitle": {
I agree, but I couldn't think of a better one - what about `imageQuote`?

2024-09-26 14:14 UTC, radoslavzeman requested changes
Shouldn't the new careers header be also added to `page.header` and in `PageHeaderSections` component?

2024-09-26 14:14 UTC, radoslavzeman commented on strapi/src/components/header-sections/careers.json
> +    },
Please take these from page title and perex.

2024-09-26 14:14 UTC, radoslavzeman commented on next/src/components/sections/headers/CareersPageHeader.tsx
> +  section: CareersHeaderSectionFragment
I just found out this:
Could we please follow the pattern for other header sections? For example `PageHeaderBranchMap.tsx`.
It uses title and perex from the page (therefore we don't need title and text in carrers header strapi component).

2024-09-26 14:15 UTC, radoslavzeman commented on next/src/components/common/Video/Video.tsx
> +        title={ariaLabel}
Hmmm, maybe it would be better to not mix and switch names and change `ariaLabel` to `iframeTitle`

2024-09-26 14:32 UTC, katarinazaprazna commented on next/src/components/common/Video/Video.tsx
> +        title={ariaLabel}
That's a good point. The `title` prop of iframe is being used by screen readers to announce the element. I can look into how our other codebases solve the iframe problem

2024-09-30 11:13 UTC, radoslavzeman commented on next/src/components/common/Video/Video.tsx
> +        title={ariaLabel}
This is completely okay solution, I just pointed out that it's not really "aria label" but "iframe title".

2024-09-30 11:25 UTC, radoslavzeman requested changes

2024-09-30 12:35 UTC, radoslavzeman approved these changes

2024-09-30 13:03 UTC, merged