#531 Create menu for mobile devices
bratislava/olo.sk pull request #587
Opened 2024-09-29 19:22 UTC by katarinazaprazna

2024-09-30 07:41 UTC, katarinazaprazna commented on next/src/components/common/Card/MenuItemArticleCard.tsx
> +// TODO: Tag should have font size of 12px
@Ty-ci is it possible to achieve this via Typography?

2024-09-30 07:43 UTC, katarinazaprazna commented on next/src/components/common/NavBar/MobileNavMenu/MobileNavMenu.tsx
> +  // TODO: Scrollbar should not be present on the mobile menu
@Ty-ci the biggest obstacle so far

2024-09-30 07:45 UTC, katarinazaprazna commented on next/src/components/common/NavBar/MobileNavMenu/MobileNavMenuContent.tsx
> +  // const { setIsMobileMegaMenuOpen } = useNavMenuContext()
@Ty-ci I added new state tracking whether the mega menu is open into `useNavMenuContext`. If it is, we'd want to hide the trigger e.g., _Odpad ->_. The code is, however, not working as expected

2024-09-30 07:46 UTC, katarinazaprazna commented on next/src/components/common/NavBar/NavMenu/NavMenuLatestArticlesList.tsx
> +export const LATEST_ARTICLES_COUNT = 6
@Ty-ci is it possible to specify this value in Strapi, perhaps?

2024-10-09 12:38 UTC, katarinazaprazna commented on next/src/components/common/NavBar/NavMenu/NavMenuLatestArticlesList.tsx
> +export const LATEST_ARTICLES_COUNT = 6
Should be reverted to the original value

2024-10-10 13:55 UTC, radoslavzeman requested changes

2024-10-10 13:55 UTC, radoslavzeman commented on next/src/components/common/Card/MenuItemArticleCard.tsx
>  type MenuItemArticleCardProps = {
Please make `tagText` optional, because when we pass empty string for those articles without tag, it causes extended gap:
![image](https://github.com/user-attachments/assets/c9a3597d-8474-4fa5-9a65-d35dc697cb8c)

2024-10-10 13:56 UTC, radoslavzeman commented on next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
>            <Icon name="telefon" className="size-6" />
solved

2024-10-10 13:56 UTC, radoslavzeman commented on next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
> +          href={href}
solved

2024-10-10 13:56 UTC, radoslavzeman commented on next/src/components/common/NavBar/MobileNavBar.tsx
> +  const { contactsLink } = data?.menu?.data?.attributes?.menuHeader ?? {}
solved

2024-10-10 13:56 UTC, radoslavzeman commented on next/src/components/common/NavBar/MobileNavBar.tsx
> +      )}
solved

2024-10-13 23:38 UTC, katarinazaprazna commented on next/src/components/common/NavBar/NavMenu/NavMenu.tsx
> +  const { data } = useQuery(generalQuery(locale))
Nothing new was added. In this file (and some others), I was re-arranging the variable definitions to organise the variables into logical groups. This is also how and why some new lines ended up getting deleted

2024-10-13 23:43 UTC, katarinazaprazna commented on next/src/components/common/Card/BasicRowCard.tsx
> +  value?: string
It's being used within the `icon-value` and `'label-value-horizontal' | 'label-value-vertical'` variant

      <div className="flex flex-col justify-center divide-y divide-border-default px-4 lg:w-2/3 lg:px-6 lg:py-3">
        {directionsBoxRows
          .filter((row) => row.value)
          .map((row) => {
            return (
              <BasicRowCard
                key={row.iconName}
                variant="icon-value"
                value={row.value!}
                iconName={row.iconName}
              />
            )
          })}
      </div>

2024-10-14 08:29 UTC, katarinazaprazna commented on next/src/components/common/NavBar/MobileNavBar.tsx
> +      <FocusTrap active={isMobileMenuOpen}>
This issue keeps occurring. None of the suggested solution in [this thread](https://stackoverflow.com/questions/71831601/ts2786-component-cannot-be-used-as-a-jsx-component) seemed to work @radoslavzeman

<img width="1126" alt="Screenshot 2024-10-14 at 10 05 49" src="https://github.com/user-attachments/assets/96588589-6ec3-411d-9d0b-8ce9a07a3bfa">

2024-10-14 11:30 UTC, katarinazaprazna commented on next/src/components/common/Card/MenuItemWorkshopCard.tsx
> +              className_onlyWhenNecessary="lg:line-clamp-1 leading-tight lg:group-hover/CardBase:underline text-wrap"
If we don't want to clamp the text in workshop cards at all, I believe it should be deleted. Looking at other cards, I only kept `text-wrap` and deleted `lg:line-clamp-1 leading-tight` :)

2024-10-15 08:41 UTC, katarinazaprazna commented on next/tailwind.config.ts
> -        mobileNavBar: '3.75rem', // 60px
<img width="482" alt="Screenshot 2024-10-14 at 09 56 12" src="https://github.com/user-attachments/assets/1fdabf9b-ac27-4cb0-b6d3-316ec4f93f57">

2024-10-16 15:54 UTC, radoslavzeman requested changes
To be able to continue in review process, please revert to the state from 10.10.2024 (commit `5a3cb29`) and add only changes related to review comments.

Please separate any other features and fixes in new PRs (animations, focus rings, refactoring that not triggered by review comments etc...)

Thank you very much for cooperation.

2024-10-18 07:41 UTC, katarinazaprazna commented on next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
> +          'pb-5': specialSectionType === 'latest_articles' || label === 'Workshopy', // To enhance readability of these sections on small devices
Discussed via Slack

2024-10-18 12:28 UTC, radoslavzeman reviewed
There is still a lot of small unrelated changes that I would better see in separate PR, such as tweaks in Typography styling. We never talked for example about need to change underline only for desktop etc.
But as it was already in state from 10.10.2024, I don't insist that it must be in separate PR. Please take it as a note for future.

2024-10-19 14:02 UTC, katarinazaprazna commented on next/src/components/common/NavBar/MobileNavMenu/MobileNavMenuTrigger.tsx
> +          label={<Typography variant="p-default-black">{label}</Typography>}
That's a great remark. However, the `icon-label` variant, which the Trigger uses, does not handle typography styling. Therefore, I believed that passing a styled text to `BasicRowCard` would be the best solution 

<img width="727" alt="Screenshot 2024-10-19 at 15 36 47" src="https://github.com/user-attachments/assets/a260d02e-0305-4d20-8c3a-2e71e3026188">

I now coded it differently, the card itself handles typography styling. Let me know what you think about it :)

2024-10-21 10:38 UTC, radoslavzeman approved these changes
I think we are finally ready 💯 🙂

2024-10-21 10:56 UTC, merged