#573 Waste collection points section
bratislava/olo.sk pull request #637
Opened 2024-10-08 11:15 UTC by katarinazaprazna

2024-10-09 10:49 UTC, radoslavzeman requested changes

2024-10-09 10:49 UTC, radoslavzeman commented on strapi/src/components/items/location-cards-item.json
> +    },
Please change to link strapi component.

Yes, content admins will probably use only url in this case.

2024-10-09 10:49 UTC, radoslavzeman commented on next/src/components/sections/WasteCollectionPointsSection.tsx
> +                    address={address ?? ''}
Please, make `address` optional in `LocationCard` instead of passing empty string.

2024-10-09 10:49 UTC, radoslavzeman commented on next/src/components/sections/WasteCollectionPointsSection.tsx
> +                <li key={title}>
Since title is not guaranteed to be unique, please use index.

2024-10-09 10:49 UTC, radoslavzeman commented on next/src/components/sections/WasteCollectionPointsSection.tsx
> +      className="py-6 lg:pb-18 lg:pt-[5.5rem]"
I'm not sure if this is needed :D but okay for this PR.

2024-10-09 10:49 UTC, radoslavzeman commented on next/src/components/sections/WasteCollectionPointsSection.tsx
> +        <ul className="grid grid-cols-1 gap-3 md:grid-cols-2 md:gap-4 lg:grid-cols-3 lg:gap-8">
Nice to think about md breakpoint! 👍 💯

2024-10-09 11:08 UTC, katarinazaprazna commented on next/src/components/sections/WasteCollectionPointsSection.tsx
> +      className="py-6 lg:pb-18 lg:pt-[5.5rem]"
It's there to create the top padding, which comes with the section container
<img width="901" alt="Screenshot 2024-10-09 at 13 05 57" src="https://github.com/user-attachments/assets/3cc4e43e-4c03-4188-b987-403faafcf712">

2024-10-10 06:30 UTC, radoslavzeman approved these changes

2024-10-10 06:54 UTC, merged